# The 30 real products, in the order the client sent them.
# imgs: IMG_ numbers, first one is the card image.
# Names corrected where the client's message was clearly a typo — flagged in the handover.

PRODUCTS = [
 dict(slug="ola-bag", ref="AT-OL1", name="AT Ola Bag", price=4090,
      category="Handbags", hide="Full-grain",
      imgs=[5850, 5849, 5851], finishes=[],
      alts=["The AT Ola Bag in black full-grain, three-quarter view, white AT monogram on the front panel",
            "The Ola Bag square to camera, showing the cut-out handle and open top",
            "The Ola Bag from the side, showing the depth of the body and the folded top edge"],
      material="Black full-grain cowhide. Cut-out handles, taken out of the panel rather than stitched on. Appliquéd AT monogram in white hide.",
      mood="An open tote that carries a laptop, a lunch and a day.",
      what="An open-top tote with the handles cut straight out of the body panel, so there is nothing to work loose. The white AT monogram is appliquéd, not printed — a second piece of hide, stitched down.",
      details=["Open top, no closure — made to be reached into",
               "Cut-out handles, taken from the body panel",
               "Appliquéd AT monogram in contrast hide",
               "Flat base, stands on its own when loaded"]),

 dict(slug="exclusive-mens-wallet", ref="AT-WL2", name="AT Exclusive Men's Wallet", price=2990,
      category="Business", hide="Ostrich",
      imgs=[5852, 5853], finishes=["Brown", "Tan", "Black"],
      alts=["Three AT Exclusive men's wallets in ostrich — brown, tan and black — laid on a cutting bench",
            "The wallets opened out, showing the quill pattern across the outer panels"],
      material="Full-quill South African ostrich. Three standing colourways: brown, tan and black.",
      mood="The one thing you carry every single day.",
      what="A bifold cut from full-quill ostrich — the prime back of the bird, where the follicles stand proud. Small enough that the quill field has to be placed exactly, which is why these are cut one at a time.",
      details=["Bifold, folded and stitched rather than glued",
               "Card slots and a full-width note section",
               "One popper-closed coin pocket on the brown and tan",
               "Quill field placed by hand on every panel"]),

 dict(slug="mini-bowling-bag", ref="AT-BB3", name="AT Mini Bowling Bag", price=2730,
      category="Handbags", hide="Full-grain",
      imgs=[5854, 5856, 5855, 5857, 5858], finishes=["Tan", "Red", "Mustard"],
      alts=["The AT Mini Bowling Bag in tan full-grain, on a sand ground, AT monogram appliquéd on the side",
            "The Mini Bowling Bag in red, three-quarter view against ochre",
            "The tan Mini Bowling Bag from the end, showing the round barrel profile",
            "The red Mini Bowling Bag with its rolled twin handles",
            "The Mini Bowling Bag in mustard with the detachable shoulder strap laid out"],
      material="Full-grain cowhide over a structured barrel body. Rolled twin handles, contrast leather corner tabs, detachable shoulder strap.",
      mood="Small, round and completely certain of itself.",
      what="A barrel bag scaled down — the shape the workshop is best known for, cut small enough to carry an evening rather than a day. The corner tabs are a second hide in a contrast colour, which is what stops the shape going soft at the ends.",
      details=["Structured barrel body, holds its round profile empty",
               "Rolled twin handles, stitched not folded",
               "Contrast leather corner tabs at both ends",
               "Detachable, adjustable shoulder strap",
               "Zip across the top, full length of the body"]),

 dict(slug="exclusive-bowling-bag", ref="AT-BB4", name="AT Exclusive Bowling Bag", price=24570,
      category="Handbags", hide="Ostrich",
      imgs=[5983, 5985, 5984, 5982, 5986], finishes=["Cobalt", "Purple"],
      alts=["The AT Exclusive Bowling Bag in cobalt ostrich against a red ground, beaded strap coiled beside it",
            "The Exclusive Bowling Bag in purple ostrich with its beaded shoulder strap",
            "The cobalt Exclusive Bowling Bag three-quarter on, showing the embossed AT monogram",
            "The cobalt bag from the end, showing the barrel profile and quill texture",
            "The purple Exclusive Bowling Bag on an ochre ground with the strap extended"],
      material="Ostrich in cobalt and purple. Embossed AT monogram. Hand-beaded webbing shoulder strap in a diamond pattern.",
      mood="The one people ask about before you have sat down.",
      what="The barrel bag at full exotic weight — ostrich dyed to colours the hide is not usually taken to, with the AT monogram embossed into the panel rather than appliquéd on top. The beaded strap is a separate piece of work again.",
      details=["Embossed AT monogram, struck into the panel",
               "Hand-beaded webbing strap, diamond pattern, detachable",
               "Structured barrel body with reinforced ends",
               "Full-length top zip with leather pulls",
               "Dyed ostrich — colour placement is checked on your hide before cutting"]),

 dict(slug="roitro-bag", ref="AT-RO5", name="AT Roitro Bag", price=2730,
      category="Handbags", hide="Full-grain",
      imgs=[5988, 5987], finishes=[],
      alts=["The AT Roitro Bag, a round dark-brown crossbody, against a red ground with its patterned strap",
            "The Roitro Bag angled, showing the embossed AT monogram across the circular face"],
      material="Dark brown full-grain, deeply burnished. Circular body. Patterned webbing strap with leather tabs.",
      mood="A circle is the hardest shape to make well in leather.",
      what="A round bag, which sounds simple and is not — the face and the gusset have to be eased together by hand the whole way round, with no straight run to hide a correction. The monogram is embossed into the face.",
      details=["Circular body, hand-eased gusset",
               "Embossed AT monogram across the face",
               "Zip around the upper half, leather pulls",
               "Patterned webbing strap on swivel clips, detachable"]),

 dict(slug="exclusive-europeana", ref="AT-EU6", name="AT Exclusive Europeana", price=4710,
      category="Handbags", hide="Ostrich",
      imgs=[5991, 5989, 5992, 5993, 5990], finishes=["Cream", "Brown"],
      alts=["The AT Exclusive Europeana in brown ostrich worn on the hip, animal-print strap over the shoulder",
            "The Exclusive Europeana in cream ostrich on a teal ground, flap closed",
            "The brown Europeana laid flat on ochre, showing the flap and the embossed monogram",
            "The brown Europeana with its patterned strap laid out full length",
            "The brown Europeana square to camera, showing the quill across the flap"],
      material="Full-quill ostrich in cream and brown. Flap front with an embossed AT monogram. Patterned webbing strap.",
      mood="Flat enough to forget you have it on.",
      what="A flat shoulder bag in full-quill ostrich, cut so the quill field runs unbroken across the flap. It sits close to the body rather than swinging, which is the whole point of the shape.",
      details=["Flap front with a concealed closure",
               "Embossed AT monogram on the flap",
               "Quill field placed to run unbroken across the front",
               "Patterned webbing strap, detachable, adjustable",
               "Slim profile — sits flat against the body"]),

 dict(slug="europeana-bag-1", ref="AT-EU7", name="AT Europeana Bag 1", price=2990,
      category="Handbags", hide="Nguni",
      imgs=[5995, 5996], finishes=["Nguni / Brown", "Nguni / Tan"],
      alts=["The AT Europeana Bag 1 with a Nguni hide-on flap and brown trim, hanging from its animal-print strap",
            "The Europeana Bag 1 with a tan leather body and Nguni flap, patterned strap over a dark ground"],
      material="Nguni hide-on flap — hair left on the skin — over a smooth leather body. Patterned webbing strap.",
      mood="No two flaps in this run are the same.",
      what="The Europeana with the flap cut from Nguni hide with the hair left on. Every Nguni skin is marked differently, so the flap is the part of the bag that will never be repeated. We cut for the marking, not for the yield.",
      details=["Hide-on Nguni flap, hair left on the skin",
               "Smooth leather body and trim",
               "Embossed AT monogram on the flap",
               "Patterned webbing strap, detachable",
               "Every flap is cut for its marking — no two match"]),

 dict(slug="europeana-bag", ref="AT-EU8", name="AT Europeana Bag", price=2600,
      category="Handbags", hide="Full-grain",
      imgs=[5999, 6002, 6004, 6001, 6006], finishes=["Pewter", "White", "Red", "Brown"],
      alts=["The AT Europeana Bag in pewter against a red ground, patterned strap coiled beside it",
            "The Europeana Bag in white with a red AT monogram and a paisley strap",
            "The Europeana Bag in white with a zebra-print strap, laid on brown leather",
            "The Europeana Bag in red on a navy ground with its patterned strap",
            "The Europeana Bag in brown on an ochre ground, strap laid out full length"],
      material="Full-grain cowhide in pewter, white, red and brown. Twin top zips. Patterned webbing strap.",
      mood="The everyday one. Four colours, one shape.",
      what="The plain-leather Europeana — the same flat, close-to-the-body shape without the exotic hide, in the four colourways the workshop keeps running. The monogram is appliquéd in a contrast hide.",
      details=["Twin top zips, separate compartments",
               "Appliquéd AT monogram in contrast hide",
               "Slim profile — sits flat against the body",
               "Patterned webbing strap, detachable, adjustable",
               "Four standing colourways"]),

 dict(slug="executive-bag", ref="AT-EX9", name="AT Executive Bag", price=72130,
      category="Business", hide="Full-grain",
      imgs=[6008, 6011, 6009, 6010], finishes=[],
      alts=["The AT Executive Bag in dark brown full-grain, standing on a Nguni hide, twin front pockets visible",
            "The Executive Bag three-quarter on, showing the rolled handles and the front pocket flaps",
            "The Executive Bag open at the top, showing the depth of the main compartment",
            "The Executive Bag from the side, showing the burnished finish across the body panel"],
      material="Dark brown full-grain, hand-burnished. Twin front pockets. Rolled handles. Structured body.",
      mood="Twenty-seven years of practice, in one bag.",
      what="The heaviest piece in the range and the one that takes the longest. A structured briefcase with twin front pockets, built on a frame so it stands square whether it is full or empty. The finish is burnished by hand, in passes, until the colour moves.",
      details=["Structured body on a frame — stands square, loaded or empty",
               "Twin front pockets with flaps",
               "Rolled handles, stitched through the body",
               "Hand-burnished finish, built up in passes",
               "Built on the main factory floor in East London"]),

 dict(slug="overnight-bag", ref="AT-OV10", name="AT Overnight Bag", price=9230,
      category="Travel", hide="Nguni",
      imgs=[6012, 6015, 6014, 6016, 6017], finishes=["Black", "Tan", "Brown"],
      alts=["The AT Overnight Bag in black with a Nguni hide-on front panel, on an ochre ground",
            "The Overnight Bag in tan with a Nguni panel and the AT monogram appliquéd across it",
            "The black Overnight Bag three-quarter on, showing the full length of the body",
            "The tan Overnight Bag from the side, showing the zip run and the end panel",
            "The Overnight Bag in brown with a Nguni panel, on an ochre ground"],
      material="Full-grain body with a hide-on Nguni front panel. Twin rolled handles. Full-length top zip.",
      mood="One night, two if you pack properly.",
      what="A soft-sided holdall with the front panel cut from Nguni hide with the hair left on. It is the bag most likely to come back to us for a strap or a lining after ten years, and the one most likely to be handed on rather than replaced.",
      details=["Hide-on Nguni front panel, hair left on the skin",
               "Appliquéd AT monogram across the panel",
               "Twin rolled handles",
               "Full-length top zip",
               "Three standing colourways"]),

 dict(slug="bowling-bag-std", ref="AT-BB11", name="AT Bowling Bag STD", price=5750,
      category="Handbags", hide="Full-grain",
      imgs=[6020, 6021], finishes=[],
      alts=["The AT Bowling Bag STD in red full-grain, large embossed AT roundel on the side",
            "The red Bowling Bag STD on a gold ground, showing the barrel profile and twin handles"],
      material="Red full-grain over a structured barrel body. Large embossed AT roundel. Contrast corner tabs.",
      mood="The full-size version of the shape that started it.",
      what="The standard barrel bag — the mini's full-size parent, with the AT mark struck into the side as a roundel rather than appliquéd. Structured throughout, so it holds the barrel shape empty.",
      details=["Structured barrel body, holds its shape empty",
               "Large embossed AT roundel on the side panel",
               "Rolled twin handles",
               "Contrast leather corner tabs",
               "Full-length top zip"]),

 dict(slug="skinny-ladys-pants", ref="AT-PT12", name="AT Skinny Lady's Pants", price=11520,
      category="Apparel", hide="Full-grain",
      imgs=[6024, 6023], finishes=[],
      alts=["The AT Skinny Lady's Pants in burgundy leather, worn, full length",
            "The Skinny Lady's Pants worn, three-quarter view, showing the leg line and the seam run"],
      material="Soft burgundy leather, panelled and seamed to follow the leg.",
      mood="Leather that moves like cloth.",
      what="Cut and seamed like a trouser rather than assembled like a bag — the panels follow the leg, and the seams do the shaping. The workshop has been making leather clothing as long as it has been making bags.",
      details=["Panelled and seamed to follow the leg",
               "Soft leather, chosen for drape rather than structure",
               "Cut to your measurements",
               "Made in the East London workshop"],
      spec_note="Made to your measurements — send us your sizing on WhatsApp and we will confirm before cutting."),

 dict(slug="roll-up-backpack", ref="AT-RU13", name="AT Roll Up Backpack", price=9250,
      category="Backpacks", hide="Full-grain",
      imgs=[6025, 6027, 6028, 6026], finishes=["Tan", "Brown"],
      alts=["The AT Roll Up Backpack in tan, roll-top closed, standing on a Nguni hide",
            "The Roll Up Backpack in brown with tan straps and an appliquéd AT monogram on the front pocket",
            "The brown Roll Up Backpack from the side, showing the roll-top and the shoulder straps",
            "The tan Roll Up Backpack laid flat with the roll-top opened out"],
      material="Full-grain in tan and brown. Roll-top closure on leather straps. Front pocket with an appliquéd AT monogram.",
      mood="Roll it down twice and it is a different bag.",
      what="A roll-top pack that changes volume with the load — closed short it is a day bag, opened out it takes a fortnight's worth. The closure is leather on leather, no plastic clips.",
      details=["Roll-top closure on leather straps — no plastic clips",
               "Volume changes with the roll",
               "Front pocket with an appliquéd AT monogram",
               "Padded shoulder straps",
               "Two standing colourways"]),

 dict(slug="man-slyng-bag", ref="AT-MS14", name="AT Man Slyng Bag", price=2850,
      category="Handbags", hide="Full-grain",
      imgs=[6030, 6029], finishes=[],
      alts=["The AT Man Slyng Bag in red full-grain on a red ground, long strap laid out above it",
            "The Man Slyng Bag angled, showing the twin zips and the embossed AT monogram"],
      material="Red full-grain. Twin zip compartments. Long adjustable webbing sling.",
      mood="Phone, wallet, keys, and nothing you do not need.",
      what="A flat sling for the things you check your pockets for. Two zipped compartments, one against the body, and a strap long enough to wear across the chest without adjusting it every time.",
      details=["Twin zip compartments, one body-side",
               "Embossed AT monogram on the front panel",
               "Long adjustable sling, worn across the body",
               "Slim enough to sit flat under a jacket"]),

 dict(slug="umthika-zebra-bag", ref="AT-UM15", name="AT Umthika Zebra Bag", price=9980,
      category="Heritage", hide="Zebra",
      imgs=[6031, 6032], finishes=[],
      alts=["The AT Umthika Zebra Bag, a rolled carrier in zebra hide with leather ties, on a white ground",
            "The Umthika Zebra Bag from above, showing the full length of the roll and the stamped end tab"],
      material="Zebra hide with the hair left on, rolled and tied with leather thongs.",
      mood="The oldest shape in the house.",
      what="Umthika is the rolled carrier — the way a mat, a stick or a set of tools has always been carried in the Eastern Cape. We make it in zebra with the hair on, tied with leather thongs rather than buckled. It is the piece in the range that is not a copy of anything European.",
      details=["Hide-on zebra, hair left on the skin",
               "Rolled carrier, tied with leather thongs",
               "Stamped leather end tab",
               "Every skin is marked differently — no two match"]),

 dict(slug="backpack-sml", ref="AT-BP16", name="AT Backpack (SML)", price=5780,
      category="Backpacks", hide="Full-grain",
      imgs=[6034, 6035, 6033, 6036], finishes=["Tan", "Brown", "Red"],
      alts=["The AT Backpack (SML) in tan on a white bench, a book and a watch beside it",
            "The Backpack (SML) in red on a chair, sunglasses and a tag beside it",
            "The Backpack (SML) in brown with tan straps, on a bench",
            "The red Backpack (SML) from the side, showing the shoulder straps and the depth"],
      material="Full-grain in tan, brown and red. Front pocket with an embossed AT monogram. Padded shoulder straps.",
      mood="A day bag that does not look like a school bag.",
      what="The small pack — cut for a tablet, a notebook and the rest of it, not for a laptop and a gym kit. Structured enough to stand up on its own when you put it down.",
      details=["Front pocket with an embossed AT monogram",
               "Padded shoulder straps",
               "Structured body — stands up when set down",
               "Top zip, full width",
               "Three standing colourways"]),

 dict(slug="mobile-suit-cover", ref="AT-MC17", name="AT Mobile Suit Cover", price=28574,
      category="Travel", hide="Full-grain",
      imgs=[6037, 6039, 6038], finishes=[],
      alts=["The AT Mobile Suit Cover in burgundy leather standing on a Nguni hide, large AT monogram on the face",
            "The Mobile Suit Cover with its telescopic handle extended, outdoors",
            "The Mobile Suit Cover on its wheels, three-quarter view, handle up"],
      material="Burgundy full-grain over a wheeled frame. Telescopic handle. Appliquéd AT monogram in tan.",
      mood="Arrive with the suit already hanging straight.",
      what="A wheeled garment carrier — a suit goes in flat and comes out without a crease across the back. Built on a frame with a telescopic handle, and skinned in full-grain rather than the nylon these are usually made from.",
      details=["Wheeled frame with a telescopic handle",
               "Carries a suit flat, no fold across the back",
               "Appliquéd AT monogram in contrast hide",
               "Full-grain throughout, no nylon",
               "The largest piece in the travel range"]),

 dict(slug="ladys-slyng-bag", ref="AT-LS18", name="AT Lady's Slyng Bag", price=1800,
      category="Handbags", hide="Nguni",
      imgs=[6040, 6043, 6042, 6045, 6044], finishes=["Red", "Pewter", "Black"],
      alts=["The AT Lady's Slyng Bag with a Nguni hide-on base and a zebra-print strap, on a red ground",
            "The Lady's Slyng Bag in red with a Nguni panel and a patterned strap",
            "The Lady's Slyng Bag in pewter with a Nguni base and an animal-print strap",
            "The Lady's Slyng Bag in black with a Nguni base, strap laid out",
            "Three Lady's Slyng Bags together — red, black and Nguni — with their straps"],
      material="Smooth leather upper with a hide-on Nguni base panel. Patterned webbing strap.",
      mood="The smallest piece we make, and the one that sells first.",
      what="A small sling with the base panel cut from Nguni hide with the hair on — the part of the bag that takes the wear, and the part that makes each one different. The lightest and most affordable way into the house.",
      details=["Hide-on Nguni base panel, hair left on the skin",
               "Smooth leather upper",
               "Appliquéd AT monogram",
               "Patterned webbing strap, detachable",
               "Three standing colourways"]),

 dict(slug="zeb-std-backpack", ref="AT-ZB19", name="AT Zeb STD Backpack", price=17640,
      category="Backpacks", hide="Zebra",
      imgs=[6046, 6048, 6047], finishes=[],
      alts=["The AT Zeb STD Backpack, zebra hide front panel with tan leather trim, against a dark ground",
            "The Zeb STD Backpack from the side, showing the zebra mane running down the panel and the tan gusset",
            "The Zeb STD Backpack from the back, showing the tan shoulder straps and padded panel"],
      material="Hide-on zebra front panel with tan full-grain body, trim and straps.",
      mood="Cut around the mane, not through it.",
      what="The standard pack with the front panel cut from a zebra skin with the hair on. The panel is placed so the mane runs down the centre — which means the panel is cut for the marking and the rest of the bag is built to fit it, rather than the other way round.",
      details=["Hide-on zebra front panel, cut around the mane",
               "Tan full-grain body, trim and shoulder straps",
               "Padded back panel and straps",
               "Top zip, full width",
               "Every skin is marked differently — no two match"]),

 dict(slug="royal-travelex", ref="AT-RT20", name="AT Royal Travelex", price=14075,
      category="Travel", hide="Nguni",
      imgs=[6051, 6049, 6050], finishes=["Tan", "Black"],
      alts=["The AT Royal Travelex in tan with Nguni hide panels, on a red ground, embossed monogram on the end",
            "The Royal Travelex in tan laid flat, showing the twin Nguni panels across the front",
            "The Royal Travelex in black with Nguni panels, three-quarter view"],
      material="Full-grain body in tan or black with twin hide-on Nguni panels across the front. Rolled handles.",
      mood="A week, carried by hand.",
      what="The large holdall — twin Nguni panels set into the front, an embossed monogram on the end, and a body cut long enough for a week rather than a weekend. It is the piece the workshop shows when it travels.",
      details=["Twin hide-on Nguni front panels",
               "Embossed AT monogram on the end panel",
               "Rolled twin handles",
               "Full-length top zip",
               "Two standing colourways"]),

 dict(slug="baby-boom-backpack", ref="AT-BM21", name="AT Baby Boom Backpack", price=8165,
      category="Backpacks", hide="Full-grain",
      imgs=[6052, 6054, 6059, 6058, 6061], finishes=[],
      alts=["The AT Baby Boom Backpack in tan full-grain, standing on a Nguni hide, embossed monogram on the front pocket",
            "The Baby Boom Backpack from the side, showing the depth and the base zip",
            "The Baby Boom Backpack worn, walking a pram along a street",
            "The Baby Boom Backpack worn over a shoulder beside a pram",
            "The Baby Boom Backpack worn, three-quarter view, beside a pram"],
      material="Tan full-grain. Front pocket with an embossed AT monogram. Base compartment on its own zip.",
      mood="A nappy bag that outlives the nappies.",
      what="Built for the first two years and cut to survive the next twenty. A separate base compartment on its own zip keeps the wet things away from everything else — and once you no longer need that, it is simply a large pack.",
      details=["Separate base compartment on its own zip",
               "Front pocket with an embossed AT monogram",
               "Padded shoulder straps",
               "Wide top opening — reachable one-handed",
               "Built to outlast what it was bought for"]),

 dict(slug="backpack-std", ref="AT-BP22", name="AT Backpack STD", price=6985,
      category="Backpacks", hide="Full-grain",
      imgs=[6064, 6062, 6065, 6063], finishes=["Black", "Red"],
      alts=["The AT Backpack STD in black full-grain, standing on a Nguni hide",
            "The Backpack STD in black, front on, showing the embossed AT monogram on the lower pocket",
            "The Backpack STD in red, open at the side, showing the laptop section",
            "The Backpack STD from the back, showing the padded panel and shoulder straps"],
      material="Full-grain in black and red. Embossed AT monogram on the front pocket. Padded back panel.",
      mood="The one you will actually use every day.",
      what="The full-size pack — a laptop section, a full-width top zip and a padded back panel. The plainest thing in the range, and the one that has to be built best, because it gets opened four times a day.",
      details=["Padded laptop section",
               "Embossed AT monogram on the front pocket",
               "Padded back panel and shoulder straps",
               "Full-width top zip",
               "Two standing colourways"]),

 dict(slug="zeb-travelex-overnight", ref="AT-ZT23", name="AT Zeb Travelex Overnight", price=33640,
      category="Travel", hide="Zebra",
      imgs=[6066], finishes=[],
      alts=["The AT Zeb Travelex Overnight in zebra hide with tan leather handles and trim"],
      material="Hide-on zebra throughout, with tan full-grain handles, trim and end panels.",
      mood="One skin, one bag, one owner.",
      what="The travel bag cut almost entirely from a single zebra skin with the hair on. Because the whole body comes off one hide, the run is limited by what the skin gives — which is why there is rarely more than one of these on the bench at a time.",
      details=["Hide-on zebra body, cut from a single skin",
               "Tan full-grain handles, trim and end panels",
               "Appliquéd AT monogram",
               "Full-length top zip",
               "Effectively a one-off — no two skins are the same"]),

 dict(slug="royal-toiletry-bag", ref="AT-TB24", name="AT Royal Toiletry Bag", price=1950,
      category="Travel", hide="Nguni",
      imgs=[6067, 6069, 6068, 6070], finishes=["Burgundy / Nguni", "Tan"],
      alts=["The AT Royal Toiletry Bag in burgundy with a Nguni hide-on side panel, on a Nguni ground",
            "The Royal Toiletry Bag in tan with an appliquéd AT monogram, on a dark ground",
            "The burgundy Toiletry Bag from the end, showing the Nguni panel and the wrist strap",
            "The tan Toiletry Bag three-quarter on, showing the full-length zip"],
      material="Full-grain with a hide-on Nguni side panel on the burgundy. Full-length zip. Wrist strap.",
      mood="The last thing packed and the first thing unpacked.",
      what="A flat-bottomed wash bag that opens the whole way along, so you can see what is in it without emptying it. Wiped out rather than washed — which is what the full-grain is for.",
      details=["Full-length zip — opens the whole way along",
               "Flat base, stands open on a shelf",
               "Hide-on Nguni side panel on the burgundy",
               "Leather wrist strap",
               "Wipe clean, no lining to perish"]),

 dict(slug="mthika-amashoba-combo", ref="AT-MA25", name="AT Mthika & Amashoba Bag", price=6080,
      category="Heritage", hide="Nguni",
      imgs=[6072, 6071], finishes=[],
      alts=["The AT Mthika and Amashoba bags together — two rolled carriers in tan leather and Nguni hide, tied with thongs",
            "The Mthika and Amashoba pair laid flat, one in olive and one in tan with a hide panel"],
      material="Full-grain and hide-on Nguni. Two rolled carriers, tied with leather thongs. Sold as a pair.",
      mood="What you carry to a ceremony, not to an office.",
      what="Sold as a pair. The mthika carries the rolled mat, the amashoba carries the ceremonial tail switches — both are shapes that existed here long before anyone in the workshop was making handbags. We build them properly rather than decoratively.",
      details=["Sold as a pair — mthika and amashoba together",
               "Rolled carriers, tied with leather thongs",
               "Hide-on Nguni panels with stamped leather tabs",
               "Full-grain body in tan and olive",
               "Made to the shapes they have always been made to"]),

 dict(slug="umthika-bag", ref="AT-UM26", name="AT Umthika Bag", price=4100,
      category="Heritage", hide="Nguni",
      imgs=[6075, 6074, 6073], finishes=[],
      alts=["The AT Umthika Bag, a burgundy rolled carrier with Nguni hide panels, on an ochre ground",
            "The Umthika Bag from above, showing the full length of the roll and the leather ties",
            "The Umthika Bag laid flat, showing the hide panels set into the body and the stamped tab"],
      material="Burgundy full-grain with hide-on Nguni panels set into the body. Leather ties. Full-length zip.",
      mood="The rolled carrier, in the house's own leather.",
      what="The umthika built in burgundy full-grain rather than hide-on — the same rolled shape, made as a piece of luggage. Nguni panels are set into the body, and a full-length zip runs the length of the roll.",
      details=["Rolled carrier with a full-length zip",
               "Hide-on Nguni panels set into the body",
               "Leather carrying ties",
               "Stamped leather end tab",
               "The everyday version of the oldest shape we make"]),

 dict(slug="opulance-clutch-bag", ref="AT-OP27", name="AT Opulance Clutch Bag", price=4680,
      category="Handbags", hide="Full-grain",
      imgs=[6077], finishes=[],
      alts=["The AT Opulance Clutch Bag in black full-grain with a large white AT monogram and a zebra-print strap, on a red ground"],
      material="Black full-grain with a large appliquéd AT monogram in white hide. Zebra-print webbing strap.",
      mood="Carried in the hand, on purpose.",
      what="A long flat clutch with the monogram taken large across the face — the one piece in the range where the mark is the design rather than a detail. The strap comes off entirely if you would rather carry it.",
      details=["Long flat clutch, carried in the hand or on the strap",
               "Large appliquéd AT monogram in contrast hide",
               "Zebra-print webbing strap, fully detachable",
               "Top zip, full length"]),

 dict(slug="dining-chair-reupholstery", ref="AT-RU28", name="AT Re-upholstery — Dining Chair", price=1780,
      category="Interiors", hide="Full-grain",
      imgs=[6078, 6079], finishes=[],
      alts=["A row of dining chairs re-upholstered in tan leather, outside the East London workshop",
            "Two re-upholstered dining chairs, close on the seat and back, showing the stitched leather"],
      material="Your chairs, re-covered in full-grain leather in the hide and colour you choose.",
      mood="The chairs are fine. It is the covering that went.",
      what="We re-cover dining chairs in leather — your frames, our hide and our stitching. The frame is stripped, the padding checked and replaced where it has gone, and the leather is cut and fitted to the chair rather than stretched over it.",
      details=["Priced per chair",
               "Your frames — stripped, checked and re-padded where needed",
               "Full-grain leather in the colour you choose",
               "Cut and fitted to the chair, not stretched over it",
               "Collection and delivery in and around East London"],
      price_note="Per chair. Send us a photograph on WhatsApp and we will confirm the figure and the turnaround.",
      spec_note="Quoted per chair once we have seen the frames."),

 dict(slug="leather-couches", ref="AT-CH29", name="AT Leather Couches", price=60000,
      category="Interiors", hide="Full-grain",
      imgs=[6086, 6085, 6083, 6082, 6084], finishes=[],
      alts=["A tan full-grain leather couch, two-seater, in a lounge",
            "The leather couch from the side, showing the length of the seat and the stitched roll arm",
            "A three-seater in the same tan full-grain, against a lounge wall",
            "The two-seater square to camera, showing the back and the arm line",
            "Close on the arm of the couch, showing the studded edge and the hand-stitched roll"],
      material="Full-grain leather over a hardwood frame. Studded arm edges. Hand-stitched roll arms.",
      mood="Furniture built by people who make bags.",
      what="Couches built in the same workshop and to the same standard as the bags — full-grain over a hardwood frame, studded along the arm edge, with the roll arms stitched by hand. Made to order in the hide and colour you choose.",
      details=["Full-grain leather over a hardwood frame",
               "Hand-stitched roll arms",
               "Studded arm edges",
               "Made to order in your choice of hide and colour",
               "Delivered and placed in and around East London"],
      price_note="From this figure, depending on size and hide. WhatsApp us with the room and we will quote it.",
      spec_note="Sizing and configuration confirmed before we start."),

 dict(slug="ostrich-slyng-lrg", ref="AT-OS30", name="AT Ostrich Slyng LRG", price=8640,
      category="Handbags", hide="Ostrich",
      imgs=[6081, 6080], finishes=[],
      alts=["The AT Ostrich Slyng LRG in tan full-quill ostrich on a green ground, embossed monogram on the front pocket",
            "The Ostrich Slyng LRG held up, showing the twin zip compartments and the quill across the panels"],
      material="Full-quill South African ostrich in tan. Twin zip compartments. Detachable sling and top handle.",
      mood="Ostrich, at a size you will actually fill.",
      what="The large sling in full-quill ostrich — twin zipped compartments, a top handle and a detachable sling, cut so the quill field runs across the front pocket as well as the body. The most hide of any bag in the range that is not luggage.",
      details=["Twin zip compartments",
               "Embossed AT monogram on the front pocket",
               "Top handle and a detachable sling",
               "Quill field placed across the front pocket and the body",
               "Full-quill South African ostrich"]),
]

# Images that are phone screenshots and need the UI chrome cropped off.
NEEDS_CROP = {6020, 6033, 6062, 6071, 6073, 6074, 6082, 6083}

CATEGORY_ORDER = ["Handbags", "Backpacks", "Travel", "Business", "Heritage", "Apparel", "Interiors"]
